-- Fiestas Radar v7 - candidatos adicionales para revisión
-- No sustituye al radar automático. Añade o actualiza candidatos sin borrar datos existentes.

insert into public.festivals (name, slug, main_genres, status, source_url, notes) values ('Primavera Sound Barcelona','primavera-sound-barcelona', array['indie','electrónica','pop'], 'active', null, 'Candidato v7 para validar con fuente oficial') on conflict (slug) do update set name=excluded.name, main_genres=coalesce(public.festivals.main_genres, excluded.main_genres);
insert into public.festival_editions (festival_id, year, city, province, region, latitude, longitude, lifecycle_stage, sales_stage, commercial_stage, ticket_status, opportunity_score, data_confidence, last_checked_at) select id, 2026, 'Barcelona', 'Barcelona', 'Cataluña', 41.4145, 2.2216, 'Detectado', 'Pendiente validar', 'nuevo', 'Pendiente', 57, 'alta', now() from public.festivals where slug = 'primavera-sound-barcelona' and not exists (select 1 from public.festival_editions fe where fe.festival_id = public.festivals.id and fe.year = 2026);

insert into public.festivals (name, slug, main_genres, status, source_url, notes) values ('Sónar Barcelona','sonar-barcelona', array['electrónica','arte digital'], 'active', null, 'Candidato v7 para validar con fuente oficial') on conflict (slug) do update set name=excluded.name, main_genres=coalesce(public.festivals.main_genres, excluded.main_genres);
insert into public.festival_editions (festival_id, year, city, province, region, latitude, longitude, lifecycle_stage, sales_stage, commercial_stage, ticket_status, opportunity_score, data_confidence, last_checked_at) select id, 2026, 'Barcelona', 'Barcelona', 'Cataluña', 41.3548, 2.1282, 'Detectado', 'Pendiente validar', 'nuevo', 'Pendiente', 57, 'alta', now() from public.festivals where slug = 'sonar-barcelona' and not exists (select 1 from public.festival_editions fe where fe.festival_id = public.festivals.id and fe.year = 2026);

insert into public.festivals (name, slug, main_genres, status, source_url, notes) values ('FIB Benicàssim','fib-benicassim', array['indie','pop','electrónica'], 'active', null, 'Candidato v7 para validar con fuente oficial') on conflict (slug) do update set name=excluded.name, main_genres=coalesce(public.festivals.main_genres, excluded.main_genres);
insert into public.festival_editions (festival_id, year, city, province, region, latitude, longitude, lifecycle_stage, sales_stage, commercial_stage, ticket_status, opportunity_score, data_confidence, last_checked_at) select id, 2026, 'Benicàssim', 'Castellón', 'Comunitat Valenciana', 40.056, 0.065, 'Detectado', 'Pendiente validar', 'nuevo', 'Pendiente', 57, 'alta', now() from public.festivals where slug = 'fib-benicassim' and not exists (select 1 from public.festival_editions fe where fe.festival_id = public.festivals.id and fe.year = 2026);

insert into public.festivals (name, slug, main_genres, status, source_url, notes) values ('Low Festival','low-festival', array['indie','pop','electrónica'], 'active', null, 'Candidato v7 para validar con fuente oficial') on conflict (slug) do update set name=excluded.name, main_genres=coalesce(public.festivals.main_genres, excluded.main_genres);
insert into public.festival_editions (festival_id, year, city, province, region, latitude, longitude, lifecycle_stage, sales_stage, commercial_stage, ticket_status, opportunity_score, data_confidence, last_checked_at) select id, 2026, 'Benidorm', 'Alicante', 'Comunitat Valenciana', 38.541, -0.123, 'Detectado', 'Pendiente validar', 'nuevo', 'Pendiente', 57, 'media', now() from public.festivals where slug = 'low-festival' and not exists (select 1 from public.festival_editions fe where fe.festival_id = public.festivals.id and fe.year = 2026);

insert into public.festivals (name, slug, main_genres, status, source_url, notes) values ('Sonorama Ribera','sonorama-ribera', array['indie','pop','rock'], 'active', null, 'Candidato v7 para validar con fuente oficial') on conflict (slug) do update set name=excluded.name, main_genres=coalesce(public.festivals.main_genres, excluded.main_genres);
insert into public.festival_editions (festival_id, year, city, province, region, latitude, longitude, lifecycle_stage, sales_stage, commercial_stage, ticket_status, opportunity_score, data_confidence, last_checked_at) select id, 2026, 'Aranda de Duero', 'Burgos', 'Castilla y León', 41.67, -3.689, 'Detectado', 'Pendiente validar', 'nuevo', 'Pendiente', 57, 'media', now() from public.festivals where slug = 'sonorama-ribera' and not exists (select 1 from public.festival_editions fe where fe.festival_id = public.festivals.id and fe.year = 2026);

insert into public.festivals (name, slug, main_genres, status, source_url, notes) values ('Mallorca Live Festival','mallorca-live-festival', array['pop','electrónica','indie'], 'active', null, 'Candidato v7 para validar con fuente oficial') on conflict (slug) do update set name=excluded.name, main_genres=coalesce(public.festivals.main_genres, excluded.main_genres);
insert into public.festival_editions (festival_id, year, city, province, region, latitude, longitude, lifecycle_stage, sales_stage, commercial_stage, ticket_status, opportunity_score, data_confidence, last_checked_at) select id, 2026, 'Calvià', 'Illes Balears', 'Illes Balears', 39.565, 2.506, 'Detectado', 'Pendiente validar', 'nuevo', 'Pendiente', 57, 'alta', now() from public.festivals where slug = 'mallorca-live-festival' and not exists (select 1 from public.festival_editions fe where fe.festival_id = public.festivals.id and fe.year = 2026);

insert into public.festivals (name, slug, main_genres, status, source_url, notes) values ('O Son do Camiño','o-son-do-camino', array['pop','rock','urbano'], 'active', null, 'Candidato v7 para validar con fuente oficial') on conflict (slug) do update set name=excluded.name, main_genres=coalesce(public.festivals.main_genres, excluded.main_genres);
insert into public.festival_editions (festival_id, year, city, province, region, latitude, longitude, lifecycle_stage, sales_stage, commercial_stage, ticket_status, opportunity_score, data_confidence, last_checked_at) select id, 2026, 'Santiago de Compostela', 'A Coruña', 'Galicia', 42.878, -8.544, 'Detectado', 'Pendiente validar', 'nuevo', 'Pendiente', 57, 'alta', now() from public.festivals where slug = 'o-son-do-camino' and not exists (select 1 from public.festival_editions fe where fe.festival_id = public.festivals.id and fe.year = 2026);

insert into public.festivals (name, slug, main_genres, status, source_url, notes) values ('Azkena Rock Festival','azkena-rock-festival', array['rock'], 'active', null, 'Candidato v7 para validar con fuente oficial') on conflict (slug) do update set name=excluded.name, main_genres=coalesce(public.festivals.main_genres, excluded.main_genres);
insert into public.festival_editions (festival_id, year, city, province, region, latitude, longitude, lifecycle_stage, sales_stage, commercial_stage, ticket_status, opportunity_score, data_confidence, last_checked_at) select id, 2026, 'Vitoria-Gasteiz', 'Álava', 'País Vasco', 42.846, -2.672, 'Detectado', 'Pendiente validar', 'nuevo', 'Pendiente', 57, 'media', now() from public.festivals where slug = 'azkena-rock-festival' and not exists (select 1 from public.festival_editions fe where fe.festival_id = public.festivals.id and fe.year = 2026);

insert into public.festivals (name, slug, main_genres, status, source_url, notes) values ('Vida Festival','vida-festival', array['indie','pop'], 'active', null, 'Candidato v7 para validar con fuente oficial') on conflict (slug) do update set name=excluded.name, main_genres=coalesce(public.festivals.main_genres, excluded.main_genres);
insert into public.festival_editions (festival_id, year, city, province, region, latitude, longitude, lifecycle_stage, sales_stage, commercial_stage, ticket_status, opportunity_score, data_confidence, last_checked_at) select id, 2026, 'Vilanova i la Geltrú', 'Barcelona', 'Cataluña', 41.224, 1.725, 'Detectado', 'Pendiente validar', 'nuevo', 'Pendiente', 57, 'media', now() from public.festivals where slug = 'vida-festival' and not exists (select 1 from public.festival_editions fe where fe.festival_id = public.festivals.id and fe.year = 2026);

insert into public.festivals (name, slug, main_genres, status, source_url, notes) values ('Canela Party','canela-party', array['indie','punk','rock'], 'active', null, 'Candidato v7 para validar con fuente oficial') on conflict (slug) do update set name=excluded.name, main_genres=coalesce(public.festivals.main_genres, excluded.main_genres);
insert into public.festival_editions (festival_id, year, city, province, region, latitude, longitude, lifecycle_stage, sales_stage, commercial_stage, ticket_status, opportunity_score, data_confidence, last_checked_at) select id, 2026, 'Torremolinos', 'Málaga', 'Andalucía', 36.621, -4.5, 'Detectado', 'Pendiente validar', 'nuevo', 'Pendiente', 57, 'media', now() from public.festivals where slug = 'canela-party' and not exists (select 1 from public.festival_editions fe where fe.festival_id = public.festivals.id and fe.year = 2026);

insert into public.festivals (name, slug, main_genres, status, source_url, notes) values ('Ebrovisión','ebrovision', array['indie','pop','rock'], 'active', null, 'Candidato v7 para validar con fuente oficial') on conflict (slug) do update set name=excluded.name, main_genres=coalesce(public.festivals.main_genres, excluded.main_genres);
insert into public.festival_editions (festival_id, year, city, province, region, latitude, longitude, lifecycle_stage, sales_stage, commercial_stage, ticket_status, opportunity_score, data_confidence, last_checked_at) select id, 2026, 'Miranda de Ebro', 'Burgos', 'Castilla y León', 42.686, -2.947, 'Detectado', 'Pendiente validar', 'nuevo', 'Pendiente', 57, 'media', now() from public.festivals where slug = 'ebrovision' and not exists (select 1 from public.festival_editions fe where fe.festival_id = public.festivals.id and fe.year = 2026);

insert into public.festivals (name, slug, main_genres, status, source_url, notes) values ('SanSan Festival','sansan-festival', array['indie','pop'], 'active', null, 'Candidato v7 para validar con fuente oficial') on conflict (slug) do update set name=excluded.name, main_genres=coalesce(public.festivals.main_genres, excluded.main_genres);
insert into public.festival_editions (festival_id, year, city, province, region, latitude, longitude, lifecycle_stage, sales_stage, commercial_stage, ticket_status, opportunity_score, data_confidence, last_checked_at) select id, 2026, 'Benicàssim', 'Castellón', 'Comunitat Valenciana', 40.056, 0.065, 'Detectado', 'Pendiente validar', 'nuevo', 'Pendiente', 57, 'media', now() from public.festivals where slug = 'sansan-festival' and not exists (select 1 from public.festival_editions fe where fe.festival_id = public.festivals.id and fe.year = 2026);

insert into public.festivals (name, slug, main_genres, status, source_url, notes) values ('Interestelar Sevilla','interstellar-sevilla', array['indie','pop','rock'], 'active', null, 'Candidato v7 para validar con fuente oficial') on conflict (slug) do update set name=excluded.name, main_genres=coalesce(public.festivals.main_genres, excluded.main_genres);
insert into public.festival_editions (festival_id, year, city, province, region, latitude, longitude, lifecycle_stage, sales_stage, commercial_stage, ticket_status, opportunity_score, data_confidence, last_checked_at) select id, 2026, 'Sevilla', 'Sevilla', 'Andalucía', 37.389, -5.984, 'Detectado', 'Pendiente validar', 'nuevo', 'Pendiente', 57, 'media', now() from public.festivals where slug = 'interstellar-sevilla' and not exists (select 1 from public.festival_editions fe where fe.festival_id = public.festivals.id and fe.year = 2026);

insert into public.festivals (name, slug, main_genres, status, source_url, notes) values ('Río Babel','rio-babel', array['pop','rock','latino'], 'active', null, 'Candidato v7 para validar con fuente oficial') on conflict (slug) do update set name=excluded.name, main_genres=coalesce(public.festivals.main_genres, excluded.main_genres);
insert into public.festival_editions (festival_id, year, city, province, region, latitude, longitude, lifecycle_stage, sales_stage, commercial_stage, ticket_status, opportunity_score, data_confidence, last_checked_at) select id, 2026, 'Rivas-Vaciamadrid', 'Madrid', 'Comunidad de Madrid', 40.34, -3.525, 'Detectado', 'Pendiente validar', 'nuevo', 'Pendiente', 57, 'media', now() from public.festivals where slug = 'rio-babel' and not exists (select 1 from public.festival_editions fe where fe.festival_id = public.festivals.id and fe.year = 2026);

insert into public.festivals (name, slug, main_genres, status, source_url, notes) values ('Tenerife Music Festival','tenerife-music-festival', array['pop','urbano'], 'active', null, 'Candidato v7 para validar con fuente oficial') on conflict (slug) do update set name=excluded.name, main_genres=coalesce(public.festivals.main_genres, excluded.main_genres);
insert into public.festival_editions (festival_id, year, city, province, region, latitude, longitude, lifecycle_stage, sales_stage, commercial_stage, ticket_status, opportunity_score, data_confidence, last_checked_at) select id, 2026, 'Santa Cruz de Tenerife', 'Tenerife', 'Canarias', 28.463, -16.251, 'Detectado', 'Pendiente validar', 'nuevo', 'Pendiente', 57, 'media', now() from public.festivals where slug = 'tenerife-music-festival' and not exists (select 1 from public.festival_editions fe where fe.festival_id = public.festivals.id and fe.year = 2026);

insert into public.festivals (name, slug, main_genres, status, source_url, notes) values ('Cranc Illa de Ibiza Festival','cranc-illa-de-ibiza', array['indie','pop'], 'active', null, 'Candidato v7 para validar con fuente oficial') on conflict (slug) do update set name=excluded.name, main_genres=coalesce(public.festivals.main_genres, excluded.main_genres);
insert into public.festival_editions (festival_id, year, city, province, region, latitude, longitude, lifecycle_stage, sales_stage, commercial_stage, ticket_status, opportunity_score, data_confidence, last_checked_at) select id, 2026, 'Ibiza', 'Illes Balears', 'Illes Balears', 38.906, 1.42, 'Detectado', 'Pendiente validar', 'nuevo', 'Pendiente', 57, 'media', now() from public.festivals where slug = 'cranc-illa-de-ibiza' and not exists (select 1 from public.festival_editions fe where fe.festival_id = public.festivals.id and fe.year = 2026);

insert into public.festivals (name, slug, main_genres, status, source_url, notes) values ('Galicia Fest','galicia-fest', array['pop','urbano'], 'active', null, 'Candidato v7 para validar con fuente oficial') on conflict (slug) do update set name=excluded.name, main_genres=coalesce(public.festivals.main_genres, excluded.main_genres);
insert into public.festival_editions (festival_id, year, city, province, region, latitude, longitude, lifecycle_stage, sales_stage, commercial_stage, ticket_status, opportunity_score, data_confidence, last_checked_at) select id, 2026, 'Santiago de Compostela', 'A Coruña', 'Galicia', 42.878, -8.544, 'Detectado', 'Pendiente validar', 'nuevo', 'Pendiente', 57, 'baja', now() from public.festivals where slug = 'galicia-fest' and not exists (select 1 from public.festival_editions fe where fe.festival_id = public.festivals.id and fe.year = 2026);

insert into public.festivals (name, slug, main_genres, status, source_url, notes) values ('Noches del Botánico','noches-del-botanico', array['jazz','pop','rock'], 'active', null, 'Candidato v7 para validar con fuente oficial') on conflict (slug) do update set name=excluded.name, main_genres=coalesce(public.festivals.main_genres, excluded.main_genres);
insert into public.festival_editions (festival_id, year, city, province, region, latitude, longitude, lifecycle_stage, sales_stage, commercial_stage, ticket_status, opportunity_score, data_confidence, last_checked_at) select id, 2026, 'Madrid', 'Madrid', 'Comunidad de Madrid', 40.445, -3.729, 'Detectado', 'Pendiente validar', 'nuevo', 'Pendiente', 57, 'media', now() from public.festivals where slug = 'noches-del-botanico' and not exists (select 1 from public.festival_editions fe where fe.festival_id = public.festivals.id and fe.year = 2026);

insert into public.festivals (name, slug, main_genres, status, source_url, notes) values ('Coca-Cola Music Experience','coca-cola-music-experience', array['pop','urbano'], 'active', null, 'Candidato v7 para validar con fuente oficial') on conflict (slug) do update set name=excluded.name, main_genres=coalesce(public.festivals.main_genres, excluded.main_genres);
insert into public.festival_editions (festival_id, year, city, province, region, latitude, longitude, lifecycle_stage, sales_stage, commercial_stage, ticket_status, opportunity_score, data_confidence, last_checked_at) select id, 2026, 'Madrid', 'Madrid', 'Comunidad de Madrid', 40.416, -3.704, 'Detectado', 'Pendiente validar', 'nuevo', 'Pendiente', 57, 'alta', now() from public.festivals where slug = 'coca-cola-music-experience' and not exists (select 1 from public.festival_editions fe where fe.festival_id = public.festivals.id and fe.year = 2026);

insert into public.festivals (name, slug, main_genres, status, source_url, notes) values ('Boombastic Asturias','boombastic-asturias', array['urbano','pop'], 'active', null, 'Candidato v7 para validar con fuente oficial') on conflict (slug) do update set name=excluded.name, main_genres=coalesce(public.festivals.main_genres, excluded.main_genres);
insert into public.festival_editions (festival_id, year, city, province, region, latitude, longitude, lifecycle_stage, sales_stage, commercial_stage, ticket_status, opportunity_score, data_confidence, last_checked_at) select id, 2026, 'Llanera', 'Asturias', 'Asturias', 43.439, -5.851, 'Detectado', 'Pendiente validar', 'nuevo', 'Pendiente', 57, 'media', now() from public.festivals where slug = 'boombastic-asturias' and not exists (select 1 from public.festival_editions fe where fe.festival_id = public.festivals.id and fe.year = 2026);

insert into public.festivals (name, slug, main_genres, status, source_url, notes) values ('Dreambeach','dreambeach', array['electrónica'], 'active', null, 'Candidato v7 para validar con fuente oficial') on conflict (slug) do update set name=excluded.name, main_genres=coalesce(public.festivals.main_genres, excluded.main_genres);
insert into public.festival_editions (festival_id, year, city, province, region, latitude, longitude, lifecycle_stage, sales_stage, commercial_stage, ticket_status, opportunity_score, data_confidence, last_checked_at) select id, 2026, 'Villaricos', 'Almería', 'Andalucía', 37.249, -1.77, 'Detectado', 'Pendiente validar', 'nuevo', 'Pendiente', 57, 'alta', now() from public.festivals where slug = 'dreambeach' and not exists (select 1 from public.festival_editions fe where fe.festival_id = public.festivals.id and fe.year = 2026);

insert into public.festivals (name, slug, main_genres, status, source_url, notes) values ('Zevra Festival','zevra-festival', array['urbano','pop','electrónica'], 'active', null, 'Candidato v7 para validar con fuente oficial') on conflict (slug) do update set name=excluded.name, main_genres=coalesce(public.festivals.main_genres, excluded.main_genres);
insert into public.festival_editions (festival_id, year, city, province, region, latitude, longitude, lifecycle_stage, sales_stage, commercial_stage, ticket_status, opportunity_score, data_confidence, last_checked_at) select id, 2026, 'Cullera', 'Valencia', 'Comunitat Valenciana', 39.166, -0.253, 'Detectado', 'Pendiente validar', 'nuevo', 'Pendiente', 57, 'alta', now() from public.festivals where slug = 'zevra-festival' and not exists (select 1 from public.festival_editions fe where fe.festival_id = public.festivals.id and fe.year = 2026);

insert into public.festivals (name, slug, main_genres, status, source_url, notes) values ('Madrid Salvaje','madrid-salvaje', array['urbano','rap'], 'active', null, 'Candidato v7 para validar con fuente oficial') on conflict (slug) do update set name=excluded.name, main_genres=coalesce(public.festivals.main_genres, excluded.main_genres);
insert into public.festival_editions (festival_id, year, city, province, region, latitude, longitude, lifecycle_stage, sales_stage, commercial_stage, ticket_status, opportunity_score, data_confidence, last_checked_at) select id, 2026, 'Madrid', 'Madrid', 'Comunidad de Madrid', 40.416, -3.704, 'Detectado', 'Pendiente validar', 'nuevo', 'Pendiente', 57, 'media', now() from public.festivals where slug = 'madrid-salvaje' and not exists (select 1 from public.festival_editions fe where fe.festival_id = public.festivals.id and fe.year = 2026);

insert into public.festivals (name, slug, main_genres, status, source_url, notes) values ('Rocanrola','rocanrola', array['rap','rock'], 'active', null, 'Candidato v7 para validar con fuente oficial') on conflict (slug) do update set name=excluded.name, main_genres=coalesce(public.festivals.main_genres, excluded.main_genres);
insert into public.festival_editions (festival_id, year, city, province, region, latitude, longitude, lifecycle_stage, sales_stage, commercial_stage, ticket_status, opportunity_score, data_confidence, last_checked_at) select id, 2026, 'Alicante', 'Alicante', 'Comunitat Valenciana', 38.345, -0.481, 'Detectado', 'Pendiente validar', 'nuevo', 'Pendiente', 57, 'media', now() from public.festivals where slug = 'rocanrola' and not exists (select 1 from public.festival_editions fe where fe.festival_id = public.festivals.id and fe.year = 2026);

insert into public.festivals (name, slug, main_genres, status, source_url, notes) values ('Aquasella','aquasella', array['techno','electrónica'], 'active', null, 'Candidato v7 para validar con fuente oficial') on conflict (slug) do update set name=excluded.name, main_genres=coalesce(public.festivals.main_genres, excluded.main_genres);
insert into public.festival_editions (festival_id, year, city, province, region, latitude, longitude, lifecycle_stage, sales_stage, commercial_stage, ticket_status, opportunity_score, data_confidence, last_checked_at) select id, 2026, 'Arriondas', 'Asturias', 'Asturias', 43.389, -5.185, 'Detectado', 'Pendiente validar', 'nuevo', 'Pendiente', 57, 'media', now() from public.festivals where slug = 'aquasella' and not exists (select 1 from public.festival_editions fe where fe.festival_id = public.festivals.id and fe.year = 2026);

insert into public.festivals (name, slug, main_genres, status, source_url, notes) values ('Riverland Fest','riverland-fest', array['urbano','electrónica'], 'active', null, 'Candidato v7 para validar con fuente oficial') on conflict (slug) do update set name=excluded.name, main_genres=coalesce(public.festivals.main_genres, excluded.main_genres);
insert into public.festival_editions (festival_id, year, city, province, region, latitude, longitude, lifecycle_stage, sales_stage, commercial_stage, ticket_status, opportunity_score, data_confidence, last_checked_at) select id, 2026, 'Arriondas', 'Asturias', 'Asturias', 43.389, -5.185, 'Detectado', 'Pendiente validar', 'nuevo', 'Pendiente', 57, 'media', now() from public.festivals where slug = 'riverland-fest' and not exists (select 1 from public.festival_editions fe where fe.festival_id = public.festivals.id and fe.year = 2026);

insert into public.festivals (name, slug, main_genres, status, source_url, notes) values ('elrow Town Madrid','elrow-town-madrid', array['electrónica'], 'active', null, 'Candidato v7 para validar con fuente oficial') on conflict (slug) do update set name=excluded.name, main_genres=coalesce(public.festivals.main_genres, excluded.main_genres);
insert into public.festival_editions (festival_id, year, city, province, region, latitude, longitude, lifecycle_stage, sales_stage, commercial_stage, ticket_status, opportunity_score, data_confidence, last_checked_at) select id, 2026, 'Madrid', 'Madrid', 'Comunidad de Madrid', 40.416, -3.704, 'Detectado', 'Pendiente validar', 'nuevo', 'Pendiente', 57, 'alta', now() from public.festivals where slug = 'elrow-town-madrid' and not exists (select 1 from public.festival_editions fe where fe.festival_id = public.festivals.id and fe.year = 2026);

insert into public.festivals (name, slug, main_genres, status, source_url, notes) values ('Weekend Beach Festival','weekend-beach-festival', array['pop','rock','electrónica'], 'active', null, 'Candidato v7 para validar con fuente oficial') on conflict (slug) do update set name=excluded.name, main_genres=coalesce(public.festivals.main_genres, excluded.main_genres);
insert into public.festival_editions (festival_id, year, city, province, region, latitude, longitude, lifecycle_stage, sales_stage, commercial_stage, ticket_status, opportunity_score, data_confidence, last_checked_at) select id, 2026, 'Torre del Mar', 'Málaga', 'Andalucía', 36.742, -4.092, 'Detectado', 'Pendiente validar', 'nuevo', 'Pendiente', 57, 'media', now() from public.festivals where slug = 'weekend-beach-festival' and not exists (select 1 from public.festival_editions fe where fe.festival_id = public.festivals.id and fe.year = 2026);

insert into public.festivals (name, slug, main_genres, status, source_url, notes) values ('WARM UP Estrella de Levante','warm-up-estrella-de-levante', array['indie','pop'], 'active', null, 'Candidato v7 para validar con fuente oficial') on conflict (slug) do update set name=excluded.name, main_genres=coalesce(public.festivals.main_genres, excluded.main_genres);
insert into public.festival_editions (festival_id, year, city, province, region, latitude, longitude, lifecycle_stage, sales_stage, commercial_stage, ticket_status, opportunity_score, data_confidence, last_checked_at) select id, 2026, 'Murcia', 'Murcia', 'Región de Murcia', 37.984, -1.129, 'Detectado', 'Pendiente validar', 'nuevo', 'Pendiente', 57, 'media', now() from public.festivals where slug = 'warm-up-estrella-de-levante' and not exists (select 1 from public.festival_editions fe where fe.festival_id = public.festivals.id and fe.year = 2026);

insert into public.festivals (name, slug, main_genres, status, source_url, notes) values ('Tomavistas','tomavistas', array['indie','pop'], 'active', null, 'Candidato v7 para validar con fuente oficial') on conflict (slug) do update set name=excluded.name, main_genres=coalesce(public.festivals.main_genres, excluded.main_genres);
insert into public.festival_editions (festival_id, year, city, province, region, latitude, longitude, lifecycle_stage, sales_stage, commercial_stage, ticket_status, opportunity_score, data_confidence, last_checked_at) select id, 2026, 'Madrid', 'Madrid', 'Comunidad de Madrid', 40.416, -3.704, 'Detectado', 'Pendiente validar', 'nuevo', 'Pendiente', 57, 'media', now() from public.festivals where slug = 'tomavistas' and not exists (select 1 from public.festival_editions fe where fe.festival_id = public.festivals.id and fe.year = 2026);

insert into public.festivals (name, slug, main_genres, status, source_url, notes) values ('Festival de les Arts','festival-de-les-arts', array['indie','pop'], 'active', null, 'Candidato v7 para validar con fuente oficial') on conflict (slug) do update set name=excluded.name, main_genres=coalesce(public.festivals.main_genres, excluded.main_genres);
insert into public.festival_editions (festival_id, year, city, province, region, latitude, longitude, lifecycle_stage, sales_stage, commercial_stage, ticket_status, opportunity_score, data_confidence, last_checked_at) select id, 2026, 'Valencia', 'Valencia', 'Comunitat Valenciana', 39.469, -0.376, 'Detectado', 'Pendiente validar', 'nuevo', 'Pendiente', 57, 'media', now() from public.festivals where slug = 'festival-de-les-arts' and not exists (select 1 from public.festival_editions fe where fe.festival_id = public.festivals.id and fe.year = 2026);

insert into public.festivals (name, slug, main_genres, status, source_url, notes) values ('Atlantic Fest','atlantic-fest', array['indie','pop'], 'active', null, 'Candidato v7 para validar con fuente oficial') on conflict (slug) do update set name=excluded.name, main_genres=coalesce(public.festivals.main_genres, excluded.main_genres);
insert into public.festival_editions (festival_id, year, city, province, region, latitude, longitude, lifecycle_stage, sales_stage, commercial_stage, ticket_status, opportunity_score, data_confidence, last_checked_at) select id, 2026, 'Vilagarcía de Arousa', 'Pontevedra', 'Galicia', 42.594, -8.765, 'Detectado', 'Pendiente validar', 'nuevo', 'Pendiente', 57, 'media', now() from public.festivals where slug = 'atlantic-fest' and not exists (select 1 from public.festival_editions fe where fe.festival_id = public.festivals.id and fe.year = 2026);

insert into public.festivals (name, slug, main_genres, status, source_url, notes) values ('Cooltural Fest','cooltural-fest', array['indie','pop'], 'active', null, 'Candidato v7 para validar con fuente oficial') on conflict (slug) do update set name=excluded.name, main_genres=coalesce(public.festivals.main_genres, excluded.main_genres);
insert into public.festival_editions (festival_id, year, city, province, region, latitude, longitude, lifecycle_stage, sales_stage, commercial_stage, ticket_status, opportunity_score, data_confidence, last_checked_at) select id, 2026, 'Almería', 'Almería', 'Andalucía', 36.834, -2.463, 'Detectado', 'Pendiente validar', 'nuevo', 'Pendiente', 57, 'media', now() from public.festivals where slug = 'cooltural-fest' and not exists (select 1 from public.festival_editions fe where fe.festival_id = public.festivals.id and fe.year = 2026);

insert into public.festivals (name, slug, main_genres, status, source_url, notes) values ('Granada Sound','granada-sound', array['indie','pop'], 'active', null, 'Candidato v7 para validar con fuente oficial') on conflict (slug) do update set name=excluded.name, main_genres=coalesce(public.festivals.main_genres, excluded.main_genres);
insert into public.festival_editions (festival_id, year, city, province, region, latitude, longitude, lifecycle_stage, sales_stage, commercial_stage, ticket_status, opportunity_score, data_confidence, last_checked_at) select id, 2026, 'Granada', 'Granada', 'Andalucía', 37.177, -3.598, 'Detectado', 'Pendiente validar', 'nuevo', 'Pendiente', 57, 'media', now() from public.festivals where slug = 'granada-sound' and not exists (select 1 from public.festival_editions fe where fe.festival_id = public.festivals.id and fe.year = 2026);

insert into public.festivals (name, slug, main_genres, status, source_url, notes) values ('PortAmérica','portamerica', array['indie','pop','gastronomía'], 'active', null, 'Candidato v7 para validar con fuente oficial') on conflict (slug) do update set name=excluded.name, main_genres=coalesce(public.festivals.main_genres, excluded.main_genres);
insert into public.festival_editions (festival_id, year, city, province, region, latitude, longitude, lifecycle_stage, sales_stage, commercial_stage, ticket_status, opportunity_score, data_confidence, last_checked_at) select id, 2026, 'Portas', 'Pontevedra', 'Galicia', 42.585, -8.664, 'Detectado', 'Pendiente validar', 'nuevo', 'Pendiente', 57, 'media', now() from public.festivals where slug = 'portamerica' and not exists (select 1 from public.festival_editions fe where fe.festival_id = public.festivals.id and fe.year = 2026);

insert into public.festivals (name, slug, main_genres, status, source_url, notes) values ('SonRías Baixas','sonrias-baixas', array['mestizaje','rock'], 'active', null, 'Candidato v7 para validar con fuente oficial') on conflict (slug) do update set name=excluded.name, main_genres=coalesce(public.festivals.main_genres, excluded.main_genres);
insert into public.festival_editions (festival_id, year, city, province, region, latitude, longitude, lifecycle_stage, sales_stage, commercial_stage, ticket_status, opportunity_score, data_confidence, last_checked_at) select id, 2026, 'Bueu', 'Pontevedra', 'Galicia', 42.324, -8.785, 'Detectado', 'Pendiente validar', 'nuevo', 'Pendiente', 57, 'media', now() from public.festivals where slug = 'sonrias-baixas' and not exists (select 1 from public.festival_editions fe where fe.festival_id = public.festivals.id and fe.year = 2026);

insert into public.festivals (name, slug, main_genres, status, source_url, notes) values ('Revenidas','revenidas', array['rock','mestizaje'], 'active', null, 'Candidato v7 para validar con fuente oficial') on conflict (slug) do update set name=excluded.name, main_genres=coalesce(public.festivals.main_genres, excluded.main_genres);
insert into public.festival_editions (festival_id, year, city, province, region, latitude, longitude, lifecycle_stage, sales_stage, commercial_stage, ticket_status, opportunity_score, data_confidence, last_checked_at) select id, 2026, 'Vilaxoán', 'Pontevedra', 'Galicia', 42.596, -8.77, 'Detectado', 'Pendiente validar', 'nuevo', 'Pendiente', 57, 'media', now() from public.festivals where slug = 'revenidas' and not exists (select 1 from public.festival_editions fe where fe.festival_id = public.festivals.id and fe.year = 2026);

insert into public.festivals (name, slug, main_genres, status, source_url, notes) values ('Pirata Beach Fest','pirata-beach-fest', array['rock','rap','mestizaje'], 'active', null, 'Candidato v7 para validar con fuente oficial') on conflict (slug) do update set name=excluded.name, main_genres=coalesce(public.festivals.main_genres, excluded.main_genres);
insert into public.festival_editions (festival_id, year, city, province, region, latitude, longitude, lifecycle_stage, sales_stage, commercial_stage, ticket_status, opportunity_score, data_confidence, last_checked_at) select id, 2026, 'Gandía', 'Valencia', 'Comunitat Valenciana', 38.968, -0.185, 'Detectado', 'Pendiente validar', 'nuevo', 'Pendiente', 57, 'media', now() from public.festivals where slug = 'pirata-beach-fest' and not exists (select 1 from public.festival_editions fe where fe.festival_id = public.festivals.id and fe.year = 2026);

insert into public.festivals (name, slug, main_genres, status, source_url, notes) values ('Leyendas del Rock','leyendas-del-rock', array['metal','rock'], 'active', null, 'Candidato v7 para validar con fuente oficial') on conflict (slug) do update set name=excluded.name, main_genres=coalesce(public.festivals.main_genres, excluded.main_genres);
insert into public.festival_editions (festival_id, year, city, province, region, latitude, longitude, lifecycle_stage, sales_stage, commercial_stage, ticket_status, opportunity_score, data_confidence, last_checked_at) select id, 2026, 'Villena', 'Alicante', 'Comunitat Valenciana', 38.637, -0.866, 'Detectado', 'Pendiente validar', 'nuevo', 'Pendiente', 57, 'media', now() from public.festivals where slug = 'leyendas-del-rock' and not exists (select 1 from public.festival_editions fe where fe.festival_id = public.festivals.id and fe.year = 2026);

insert into public.festivals (name, slug, main_genres, status, source_url, notes) values ('Rabolagartija','rabolagartija', array['rock','mestizaje'], 'active', null, 'Candidato v7 para validar con fuente oficial') on conflict (slug) do update set name=excluded.name, main_genres=coalesce(public.festivals.main_genres, excluded.main_genres);
insert into public.festival_editions (festival_id, year, city, province, region, latitude, longitude, lifecycle_stage, sales_stage, commercial_stage, ticket_status, opportunity_score, data_confidence, last_checked_at) select id, 2026, 'Villena', 'Alicante', 'Comunitat Valenciana', 38.637, -0.866, 'Detectado', 'Pendiente validar', 'nuevo', 'Pendiente', 57, 'media', now() from public.festivals where slug = 'rabolagartija' and not exists (select 1 from public.festival_editions fe where fe.festival_id = public.festivals.id and fe.year = 2026);

insert into public.festivals (name, slug, main_genres, status, source_url, notes) values ('Barcelona Beach Festival','bbf-barcelona-beach-festival', array['electrónica'], 'active', null, 'Candidato v7 para validar con fuente oficial') on conflict (slug) do update set name=excluded.name, main_genres=coalesce(public.festivals.main_genres, excluded.main_genres);
insert into public.festival_editions (festival_id, year, city, province, region, latitude, longitude, lifecycle_stage, sales_stage, commercial_stage, ticket_status, opportunity_score, data_confidence, last_checked_at) select id, 2026, 'Barcelona', 'Barcelona', 'Cataluña', 41.414, 2.221, 'Detectado', 'Pendiente validar', 'nuevo', 'Pendiente', 57, 'media', now() from public.festivals where slug = 'bbf-barcelona-beach-festival' and not exists (select 1 from public.festival_editions fe where fe.festival_id = public.festivals.id and fe.year = 2026);

insert into public.festivals (name, slug, main_genres, status, source_url, notes) values ('Brunch Electronik Festival','brunch-electronik-festival', array['electrónica'], 'active', null, 'Candidato v7 para validar con fuente oficial') on conflict (slug) do update set name=excluded.name, main_genres=coalesce(public.festivals.main_genres, excluded.main_genres);
insert into public.festival_editions (festival_id, year, city, province, region, latitude, longitude, lifecycle_stage, sales_stage, commercial_stage, ticket_status, opportunity_score, data_confidence, last_checked_at) select id, 2026, 'Barcelona', 'Barcelona', 'Cataluña', 41.387, 2.169, 'Detectado', 'Pendiente validar', 'nuevo', 'Pendiente', 57, 'media', now() from public.festivals where slug = 'brunch-electronik-festival' and not exists (select 1 from public.festival_editions fe where fe.festival_id = public.festivals.id and fe.year = 2026);

insert into public.festivals (name, slug, main_genres, status, source_url, notes) values ('DGTL Barcelona','dgtl-barcelona', array['electrónica'], 'active', null, 'Candidato v7 para validar con fuente oficial') on conflict (slug) do update set name=excluded.name, main_genres=coalesce(public.festivals.main_genres, excluded.main_genres);
insert into public.festival_editions (festival_id, year, city, province, region, latitude, longitude, lifecycle_stage, sales_stage, commercial_stage, ticket_status, opportunity_score, data_confidence, last_checked_at) select id, 2026, 'Barcelona', 'Barcelona', 'Cataluña', 41.414, 2.221, 'Detectado', 'Pendiente validar', 'nuevo', 'Pendiente', 57, 'media', now() from public.festivals where slug = 'dgtl-barcelona' and not exists (select 1 from public.festival_editions fe where fe.festival_id = public.festivals.id and fe.year = 2026);

insert into public.festivals (name, slug, main_genres, status, source_url, notes) values ('Marenostrum Fuengirola','mar-nostrum-fuengirola', array['pop','rock','urbano'], 'active', null, 'Candidato v7 para validar con fuente oficial') on conflict (slug) do update set name=excluded.name, main_genres=coalesce(public.festivals.main_genres, excluded.main_genres);
insert into public.festival_editions (festival_id, year, city, province, region, latitude, longitude, lifecycle_stage, sales_stage, commercial_stage, ticket_status, opportunity_score, data_confidence, last_checked_at) select id, 2026, 'Fuengirola', 'Málaga', 'Andalucía', 36.54, -4.624, 'Detectado', 'Pendiente validar', 'nuevo', 'Pendiente', 57, 'media', now() from public.festivals where slug = 'mar-nostrum-fuengirola' and not exists (select 1 from public.festival_editions fe where fe.festival_id = public.festivals.id and fe.year = 2026);

insert into public.festivals (name, slug, main_genres, status, source_url, notes) values ('Animal Sound','animal-sound', array['electrónica','urbano'], 'active', null, 'Candidato v7 para validar con fuente oficial') on conflict (slug) do update set name=excluded.name, main_genres=coalesce(public.festivals.main_genres, excluded.main_genres);
insert into public.festival_editions (festival_id, year, city, province, region, latitude, longitude, lifecycle_stage, sales_stage, commercial_stage, ticket_status, opportunity_score, data_confidence, last_checked_at) select id, 2026, 'Murcia', 'Murcia', 'Región de Murcia', 37.984, -1.129, 'Detectado', 'Pendiente validar', 'nuevo', 'Pendiente', 57, 'media', now() from public.festivals where slug = 'animal-sound' and not exists (select 1 from public.festival_editions fe where fe.festival_id = public.festivals.id and fe.year = 2026);

insert into public.festivals (name, slug, main_genres, status, source_url, notes) values ('FIV Vilalba','fiv-vilalba', array['indie','pop'], 'active', null, 'Candidato v7 para validar con fuente oficial') on conflict (slug) do update set name=excluded.name, main_genres=coalesce(public.festivals.main_genres, excluded.main_genres);
insert into public.festival_editions (festival_id, year, city, province, region, latitude, longitude, lifecycle_stage, sales_stage, commercial_stage, ticket_status, opportunity_score, data_confidence, last_checked_at) select id, 2026, 'Vilalba', 'Lugo', 'Galicia', 43.298, -7.681, 'Detectado', 'Pendiente validar', 'nuevo', 'Pendiente', 57, 'media', now() from public.festivals where slug = 'fiv-vilalba' and not exists (select 1 from public.festival_editions fe where fe.festival_id = public.festivals.id and fe.year = 2026);

insert into public.festivals (name, slug, main_genres, status, source_url, notes) values ('MUWI La Rioja','muwi-la-rioja', array['indie','pop'], 'active', null, 'Candidato v7 para validar con fuente oficial') on conflict (slug) do update set name=excluded.name, main_genres=coalesce(public.festivals.main_genres, excluded.main_genres);
insert into public.festival_editions (festival_id, year, city, province, region, latitude, longitude, lifecycle_stage, sales_stage, commercial_stage, ticket_status, opportunity_score, data_confidence, last_checked_at) select id, 2026, 'Logroño', 'La Rioja', 'La Rioja', 42.462, -2.445, 'Detectado', 'Pendiente validar', 'nuevo', 'Pendiente', 57, 'media', now() from public.festivals where slug = 'muwi-la-rioja' and not exists (select 1 from public.festival_editions fe where fe.festival_id = public.festivals.id and fe.year = 2026);

insert into public.festivals (name, slug, main_genres, status, source_url, notes) values ('Planeta Sound','planeta-sound', array['indie','pop'], 'active', null, 'Candidato v7 para validar con fuente oficial') on conflict (slug) do update set name=excluded.name, main_genres=coalesce(public.festivals.main_genres, excluded.main_genres);
insert into public.festival_editions (festival_id, year, city, province, region, latitude, longitude, lifecycle_stage, sales_stage, commercial_stage, ticket_status, opportunity_score, data_confidence, last_checked_at) select id, 2026, 'Ponferrada', 'León', 'Castilla y León', 42.546, -6.596, 'Detectado', 'Pendiente validar', 'nuevo', 'Pendiente', 57, 'media', now() from public.festivals where slug = 'planeta-sound' and not exists (select 1 from public.festival_editions fe where fe.festival_id = public.festivals.id and fe.year = 2026);

insert into public.festivals (name, slug, main_genres, status, source_url, notes) values ('Río Verbena Fest','rio-verbena-fest', array['pop','rock','urbano'], 'active', null, 'Candidato v7 para validar con fuente oficial') on conflict (slug) do update set name=excluded.name, main_genres=coalesce(public.festivals.main_genres, excluded.main_genres);
insert into public.festival_editions (festival_id, year, city, province, region, latitude, longitude, lifecycle_stage, sales_stage, commercial_stage, ticket_status, opportunity_score, data_confidence, last_checked_at) select id, 2026, 'Pontevedra', 'Pontevedra', 'Galicia', 42.43, -8.644, 'Detectado', 'Pendiente validar', 'nuevo', 'Pendiente', 57, 'media', now() from public.festivals where slug = 'rio-verbena-fest' and not exists (select 1 from public.festival_editions fe where fe.festival_id = public.festivals.id and fe.year = 2026);

insert into public.festivals (name, slug, main_genres, status, source_url, notes) values ('Morrina Festival','morrina-festival', array['pop','urbano'], 'active', null, 'Candidato v7 para validar con fuente oficial') on conflict (slug) do update set name=excluded.name, main_genres=coalesce(public.festivals.main_genres, excluded.main_genres);
insert into public.festival_editions (festival_id, year, city, province, region, latitude, longitude, lifecycle_stage, sales_stage, commercial_stage, ticket_status, opportunity_score, data_confidence, last_checked_at) select id, 2026, 'A Coruña', 'A Coruña', 'Galicia', 43.362, -8.411, 'Detectado', 'Pendiente validar', 'nuevo', 'Pendiente', 57, 'media', now() from public.festivals where slug = 'morrina-festival' and not exists (select 1 from public.festival_editions fe where fe.festival_id = public.festivals.id and fe.year = 2026);

insert into public.festivals (name, slug, main_genres, status, source_url, notes) values ('Arrecife en Vivo','arrecife-en-vivo', array['rock','indie'], 'active', null, 'Candidato v7 para validar con fuente oficial') on conflict (slug) do update set name=excluded.name, main_genres=coalesce(public.festivals.main_genres, excluded.main_genres);
insert into public.festival_editions (festival_id, year, city, province, region, latitude, longitude, lifecycle_stage, sales_stage, commercial_stage, ticket_status, opportunity_score, data_confidence, last_checked_at) select id, 2026, 'Arrecife', 'Las Palmas', 'Canarias', 28.963, -13.547, 'Detectado', 'Pendiente validar', 'nuevo', 'Pendiente', 57, 'media', now() from public.festivals where slug = 'arrecife-en-vivo' and not exists (select 1 from public.festival_editions fe where fe.festival_id = public.festivals.id and fe.year = 2026);
