import type { Contact, FestivalOverview, Proposal, RadarAlert } from "./types";

export const mockFestivals: FestivalOverview[] = [
  {
    festival_id: "demo-mad-cool",
    edition_id: "edition-mad-cool-2026",
    name: "Mad Cool Festival",
    slug: "mad-cool-festival",
    official_website: "https://madcoolfestival.es",
    instagram_url: "https://instagram.com/madcoolfestival",
    main_genres: ["indie", "pop", "rock"],
    year: 2026,
    start_date: "2026-07-08",
    end_date: "2026-07-11",
    venue_name: "Recinto festival",
    city: "Madrid",
    province: "Madrid",
    region: "Comunidad de Madrid",
    latitude: 40.4168,
    longitude: -3.7038,
    avg_attendance: 70000,
    expected_attendance: 82000,
    sales_stage: "Tramo 2",
    lifecycle_stage: "Venta activa",
    ticket_status: "Disponible",
    opportunity_score: 91,
    last_checked_at: new Date().toISOString(),
    data_confidence: "media"
  },
  {
    festival_id: "demo-arenal",
    edition_id: "edition-arenal-2026",
    name: "Arenal Sound",
    slug: "arenal-sound",
    official_website: "https://www.arenalsound.com",
    instagram_url: "https://instagram.com/arenalsound",
    main_genres: ["urbano", "pop", "electrónica"],
    year: 2026,
    start_date: "2026-07-28",
    end_date: "2026-08-02",
    venue_name: "Playa El Arenal",
    city: "Burriana",
    province: "Castellón",
    region: "Comunitat Valenciana",
    latitude: 39.8896,
    longitude: -0.0849,
    avg_attendance: 55000,
    expected_attendance: 60000,
    sales_stage: "Últimos abonos",
    lifecycle_stage: "Venta avanzada",
    ticket_status: "Alta demanda",
    opportunity_score: 86,
    last_checked_at: new Date().toISOString(),
    data_confidence: "baja"
  },
  {
    festival_id: "demo-cruilla",
    edition_id: "edition-cruilla-2026",
    name: "Festival Cruïlla",
    slug: "festival-cruilla",
    official_website: "https://www.cruillabarcelona.com",
    instagram_url: "https://instagram.com/festivalcruilla",
    main_genres: ["pop", "indie", "mestizaje"],
    year: 2026,
    start_date: "2026-07-09",
    end_date: "2026-07-12",
    venue_name: "Parc del Fòrum",
    city: "Barcelona",
    province: "Barcelona",
    region: "Cataluña",
    latitude: 41.3851,
    longitude: 2.1734,
    avg_attendance: 45000,
    expected_attendance: 50000,
    sales_stage: "Cartel parcial",
    lifecycle_stage: "Comunicación activa",
    ticket_status: "Disponible",
    opportunity_score: 79,
    last_checked_at: new Date().toISOString(),
    data_confidence: "media"
  },
  {
    festival_id: "demo-bbk",
    edition_id: "edition-bbk-2026",
    name: "Bilbao BBK Live",
    slug: "bilbao-bbk-live",
    official_website: "https://bilbaobbklive.com",
    instagram_url: "https://instagram.com/bilbaobbklive",
    main_genres: ["indie", "rock", "electrónica"],
    year: 2026,
    start_date: "2026-07-09",
    end_date: "2026-07-11",
    venue_name: "Kobetamendi",
    city: "Bilbao",
    province: "Bizkaia",
    region: "País Vasco",
    latitude: 43.2630,
    longitude: -2.9350,
    avg_attendance: 40000,
    expected_attendance: 44000,
    sales_stage: "Tramo 1",
    lifecycle_stage: "Venta activa",
    ticket_status: "Disponible",
    opportunity_score: 75,
    last_checked_at: new Date().toISOString(),
    data_confidence: "baja"
  },
  {
    festival_id: "demo-sonar",
    edition_id: "edition-sonar-2026",
    name: "Sónar Barcelona",
    slug: "sonar-barcelona",
    official_website: "https://sonar.es",
    instagram_url: "https://instagram.com/sonarfestival",
    main_genres: ["electrónica", "arte digital"],
    year: 2026,
    start_date: "2026-06-18",
    end_date: "2026-06-20",
    venue_name: "Barcelona",
    city: "Barcelona",
    province: "Barcelona",
    region: "Cataluña",
    latitude: 41.3851,
    longitude: 2.1734,
    avg_attendance: 120000,
    expected_attendance: 125000,
    sales_stage: "Fechas anunciadas",
    lifecycle_stage: "Preventa",
    ticket_status: "Pendiente",
    opportunity_score: 72,
    last_checked_at: new Date().toISOString(),
    data_confidence: "baja"
  },
  {
    festival_id: "demo-viñarock",
    edition_id: "edition-vinarock-2026",
    name: "Viña Rock",
    slug: "vina-rock",
    official_website: "https://www.vina-rock.com",
    instagram_url: "https://instagram.com/vinarockoficial",
    main_genres: ["rock", "rap", "mestizaje"],
    year: 2026,
    start_date: "2026-04-30",
    end_date: "2026-05-02",
    venue_name: "Villarrobledo",
    city: "Villarrobledo",
    province: "Albacete",
    region: "Castilla-La Mancha",
    latitude: 39.2699,
    longitude: -2.6012,
    avg_attendance: 75000,
    expected_attendance: 78000,
    sales_stage: "Post-evento",
    lifecycle_stage: "Recontactar próxima edición",
    ticket_status: "Cerrado",
    opportunity_score: 64,
    last_checked_at: new Date().toISOString(),
    data_confidence: "baja"
  }
];

export const mockContacts: Contact[] = [
  {
    id: "contact-1",
    name: "Responsable Marketing Demo",
    role: "Marketing / campañas",
    company: "Promotora demo",
    email: "marketing@example.com",
    phone: "+34 600 000 000",
    instagram: "@marketing_demo",
    source: "manual",
    legal_basis: "contacto profesional",
    notes: "Contacto demo para probar propuestas. Sustituir por datos reales."
  },
  {
    id: "contact-2",
    name: "Responsable Patrocinios Demo",
    role: "Patrocinios",
    company: "Agencia demo",
    email: "sponsors@example.com",
    instagram: "@sponsors_demo",
    source: "manual",
    legal_basis: "contacto profesional"
  }
];

export const mockAlerts: RadarAlert[] = [
  {
    id: "alert-1",
    festival_id: "demo-arenal",
    festival_name: "Arenal Sound",
    title: "Cambio de tramo detectado",
    description: "La ficha demo está en últimos abonos. Revisar y contactar esta semana.",
    severity: "high",
    status: "open",
    created_at: new Date().toISOString()
  },
  {
    id: "alert-2",
    festival_id: "demo-cruilla",
    festival_name: "Festival Cruïlla",
    title: "Cartel parcial activo",
    description: "Buen momento para propuesta de contenido previa al festival.",
    severity: "medium",
    status: "open",
    created_at: new Date().toISOString()
  }
];

export const mockProposals: Proposal[] = [
  {
    id: "proposal-1",
    festival_id: "demo-mad-cool",
    festival_name: "Mad Cool Festival",
    channel: "email",
    objective: "colaboración contenido",
    subject: "Propuesta de colaboración con @fiestas_es",
    body: "Hola, equipo. Somos @fiestas_es y queremos explorar una colaboración de contenido para vuestra próxima edición.",
    status: "draft",
    created_at: new Date().toISOString()
  }
];
